// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"user", "service_account"}, Default: "user"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "enabled"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "user_id", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_projects_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[10]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_keys_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[11]},
			},
			{
				Name:    "api_keys_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10]},
			},
			{
				Name:    "api_keys_by_key",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai", "openai_responses", "codex", "vercel", "anthropic", "anthropic_aws", "anthropic_gcp", "gemini_openai", "gemini", "gemini_vertex", "deepseek", "deepseek_anthropic", "deepinfra", "doubao", "doubao_anthropic", "moonshot", "moonshot_anthropic", "zhipu", "zai", "zhipu_anthropic", "zai_anthropic", "anthropic_fake", "openai_fake", "openrouter", "xiaomi", "xai", "ppio", "siliconflow", "volcengine", "longcat", "longcat_anthropic", "minimax", "minimax_anthropic", "aihubmix", "burncloud", "modelscope", "bailian", "jina", "github", "claudecode", "cerebras", "antigravity", "nanogpt"}},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "credentials", Type: field.TypeJSON},
		{Name: "disabled_api_keys", Type: field.TypeJSON, Nullable: true},
		{Name: "supported_models", Type: field.TypeJSON},
		{Name: "manual_models", Type: field.TypeJSON, Nullable: true},
		{Name: "auto_sync_supported_models", Type: field.TypeBool, Default: false},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "default_test_model", Type: field.TypeString},
		{Name: "policies", Type: field.TypeJSON, Nullable: true},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "ordering_weight", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channels_by_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelsColumns[6], ChannelsColumns[3]},
			},
		},
	}
	// ChannelModelPricesColumns holds the columns for the "channel_model_prices" table.
	ChannelModelPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON},
		{Name: "reference_id", Type: field.TypeString, Unique: true},
		{Name: "channel_id", Type: field.TypeInt},
	}
	// ChannelModelPricesTable holds the schema information for the "channel_model_prices" table.
	ChannelModelPricesTable = &schema.Table{
		Name:       "channel_model_prices",
		Columns:    ChannelModelPricesColumns,
		PrimaryKey: []*schema.Column{ChannelModelPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_model_prices_channels_channel_model_prices",
				Columns:    []*schema.Column{ChannelModelPricesColumns[7]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_model_prices_by_channel_id_model_id",
				Unique:  true,
				Columns: []*schema.Column{ChannelModelPricesColumns[7], ChannelModelPricesColumns[4], ChannelModelPricesColumns[3]},
			},
		},
	}
	// ChannelModelPriceVersionsColumns holds the columns for the "channel_model_price_versions" table.
	ChannelModelPriceVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "model_id", Type: field.TypeString},
		{Name: "price", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}},
		{Name: "effective_start_at", Type: field.TypeTime},
		{Name: "effective_end_at", Type: field.TypeTime, Nullable: true},
		{Name: "reference_id", Type: field.TypeString, Unique: true},
		{Name: "channel_model_price_id", Type: field.TypeInt},
	}
	// ChannelModelPriceVersionsTable holds the schema information for the "channel_model_price_versions" table.
	ChannelModelPriceVersionsTable = &schema.Table{
		Name:       "channel_model_price_versions",
		Columns:    ChannelModelPriceVersionsColumns,
		PrimaryKey: []*schema.Column{ChannelModelPriceVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_model_price_versions_channel_model_prices_versions",
				Columns:    []*schema.Column{ChannelModelPriceVersionsColumns[10]},
				RefColumns: []*schema.Column{ChannelModelPricesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChannelOverrideTemplatesColumns holds the columns for the "channel_override_templates" table.
	ChannelOverrideTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "override_parameters", Type: field.TypeString, Default: "{}"},
		{Name: "override_headers", Type: field.TypeJSON},
		{Name: "header_override_operations", Type: field.TypeJSON, Nullable: true},
		{Name: "body_override_operations", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ChannelOverrideTemplatesTable holds the schema information for the "channel_override_templates" table.
	ChannelOverrideTemplatesTable = &schema.Table{
		Name:       "channel_override_templates",
		Columns:    ChannelOverrideTemplatesColumns,
		PrimaryKey: []*schema.Column{ChannelOverrideTemplatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_override_templates_users_channel_override_templates",
				Columns:    []*schema.Column{ChannelOverrideTemplatesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_override_templates_by_user_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelOverrideTemplatesColumns[10], ChannelOverrideTemplatesColumns[4], ChannelOverrideTemplatesColumns[3]},
			},
		},
	}
	// ChannelProbesColumns holds the columns for the "channel_probes" table.
	ChannelProbesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "total_request_count", Type: field.TypeInt},
		{Name: "success_request_count", Type: field.TypeInt},
		{Name: "avg_tokens_per_second", Type: field.TypeFloat64, Nullable: true},
		{Name: "avg_time_to_first_token_ms", Type: field.TypeFloat64, Nullable: true},
		{Name: "timestamp", Type: field.TypeInt64},
		{Name: "channel_id", Type: field.TypeInt},
	}
	// ChannelProbesTable holds the schema information for the "channel_probes" table.
	ChannelProbesTable = &schema.Table{
		Name:       "channel_probes",
		Columns:    ChannelProbesColumns,
		PrimaryKey: []*schema.Column{ChannelProbesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_probes_channels_channel_probes",
				Columns:    []*schema.Column{ChannelProbesColumns[6]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "channel_probes_by_channel_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{ChannelProbesColumns[6], ChannelProbesColumns[5]},
			},
		},
	}
	// DataStoragesColumns holds the columns for the "data_storages" table.
	DataStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "primary", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"database", "fs", "s3", "gcs", "webdav"}},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
	}
	// DataStoragesTable holds the schema information for the "data_storages" table.
	DataStoragesTable = &schema.Table{
		Name:       "data_storages",
		Columns:    DataStoragesColumns,
		PrimaryKey: []*schema.Column{DataStoragesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "data_sources_by_name",
				Unique:  true,
				Columns: []*schema.Column{DataStoragesColumns[4]},
			},
		},
	}
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "developer", Type: field.TypeString},
		{Name: "model_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"chat", "embedding", "rerank"}, Default: "chat"},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString},
		{Name: "group", Type: field.TypeString},
		{Name: "model_card", Type: field.TypeJSON},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "remark", Type: field.TypeString, Nullable: true},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "models_by_name",
				Unique:  true,
				Columns: []*schema.Column{ModelsColumns[7], ModelsColumns[3]},
			},
			{
				Name:    "models_by_model_id",
				Unique:  true,
				Columns: []*schema.Column{ModelsColumns[5], ModelsColumns[3]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "projects_by_name",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[4]},
			},
		},
	}
	// PromptsColumns holds the columns for the "prompts" table.
	PromptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled"}, Default: "disabled"},
		{Name: "order", Type: field.TypeInt, Default: 0},
		{Name: "settings", Type: field.TypeJSON},
	}
	// PromptsTable holds the schema information for the "prompts" table.
	PromptsTable = &schema.Table{
		Name:       "prompts",
		Columns:    PromptsColumns,
		PrimaryKey: []*schema.Column{PromptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "prompts_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{PromptsColumns[4]},
			},
			{
				Name:    "prompts_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{PromptsColumns[4], PromptsColumns[5], PromptsColumns[3]},
			},
		},
	}
	// ProviderQuotaStatusColumns holds the columns for the "provider_quota_status" table.
	ProviderQuotaStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "provider_type", Type: field.TypeEnum, Enums: []string{"claudecode", "codex"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"available", "warning", "exhausted", "unknown"}},
		{Name: "quota_data", Type: field.TypeJSON},
		{Name: "next_reset_at", Type: field.TypeTime, Nullable: true},
		{Name: "ready", Type: field.TypeBool, Default: true},
		{Name: "next_check_at", Type: field.TypeTime},
		{Name: "channel_id", Type: field.TypeInt, Unique: true},
	}
	// ProviderQuotaStatusTable holds the schema information for the "provider_quota_status" table.
	ProviderQuotaStatusTable = &schema.Table{
		Name:       "provider_quota_status",
		Columns:    ProviderQuotaStatusColumns,
		PrimaryKey: []*schema.Column{ProviderQuotaStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "provider_quota_status_channels_provider_quota_status",
				Columns:    []*schema.Column{ProviderQuotaStatusColumns[10]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "providerquotastatus_channel_id",
				Unique:  true,
				Columns: []*schema.Column{ProviderQuotaStatusColumns[10]},
			},
			{
				Name:    "providerquotastatus_next_check_at",
				Unique:  false,
				Columns: []*schema.Column{ProviderQuotaStatusColumns[9]},
			},
		},
	}
	// QuotaTransactionsColumns holds the columns for the "quota_transactions" table.
	QuotaTransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"recharge", "consume", "refund", "reward"}},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "balance_after", Type: field.TypeInt64},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "order_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "completed", "failed"}, Default: "completed"},
	}
	// QuotaTransactionsTable holds the schema information for the "quota_transactions" table.
	QuotaTransactionsTable = &schema.Table{
		Name:       "quota_transactions",
		Columns:    QuotaTransactionsColumns,
		PrimaryKey: []*schema.Column{QuotaTransactionsColumns[0]},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_headers", Type: field.TypeJSON, Nullable: true},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "client_ip", Type: field.TypeString, Default: ""},
		{Name: "metrics_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_first_token_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "trace_id", Type: field.TypeInt, Nullable: true},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_api_keys_requests",
				Columns:    []*schema.Column{RequestsColumns[16]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_channels_requests",
				Columns:    []*schema.Column{RequestsColumns[17]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_data_storages_requests",
				Columns:    []*schema.Column{RequestsColumns[18]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_projects_requests",
				Columns:    []*schema.Column{RequestsColumns[19]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "requests_traces_requests",
				Columns:    []*schema.Column{RequestsColumns[20]},
				RefColumns: []*schema.Column{TracesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requests_by_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[16], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_project_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[19], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[17], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_trace_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[20], RequestsColumns[1]},
			},
			{
				Name:    "requests_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[1]},
			},
		},
	}
	// RequestExecutionsColumns holds the columns for the "request_executions" table.
	RequestExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed", "canceled"}},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "metrics_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "metrics_first_token_latency_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "request_headers", Type: field.TypeJSON, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "data_storage_id", Type: field.TypeInt, Nullable: true},
		{Name: "request_id", Type: field.TypeInt},
	}
	// RequestExecutionsTable holds the schema information for the "request_executions" table.
	RequestExecutionsTable = &schema.Table{
		Name:       "request_executions",
		Columns:    RequestExecutionsColumns,
		PrimaryKey: []*schema.Column{RequestExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_executions_channels_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[16]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_data_storages_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[17]},
				RefColumns: []*schema.Column{DataStoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "request_executions_requests_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[18]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_executions_by_request_id_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[18], RequestExecutionsColumns[11], RequestExecutionsColumns[1]},
			},
			{
				Name:    "request_executions_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[16]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"system", "project"}, Default: "system"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_projects_roles",
				Columns:    []*schema.Column{RolesColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "roles_by_project_id_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[7], RolesColumns[4]},
			},
			{
				Name:    "roles_by_level",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[5]},
			},
		},
	}
	// SubscriptionPlansColumns holds the columns for the "subscription_plans" table.
	SubscriptionPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "price", Type: field.TypeInt64},
		{Name: "currency", Type: field.TypeString, Default: "CNY"},
		{Name: "quota", Type: field.TypeInt64},
		{Name: "duration_days", Type: field.TypeInt64},
		{Name: "features", Type: field.TypeJSON, Nullable: true},
		{Name: "is_popular", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeBool, Default: true},
	}
	// SubscriptionPlansTable holds the schema information for the "subscription_plans" table.
	SubscriptionPlansTable = &schema.Table{
		Name:       "subscription_plans",
		Columns:    SubscriptionPlansColumns,
		PrimaryKey: []*schema.Column{SubscriptionPlansColumns[0]},
	}
	// SystemsColumns holds the columns for the "systems" table.
	SystemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"mysql": "mediumtext"}},
	}
	// SystemsTable holds the schema information for the "systems" table.
	SystemsTable = &schema.Table{
		Name:       "systems",
		Columns:    SystemsColumns,
		PrimaryKey: []*schema.Column{SystemsColumns[0]},
	}
	// ThreadsColumns holds the columns for the "threads" table.
	ThreadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "thread_id", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
	}
	// ThreadsTable holds the schema information for the "threads" table.
	ThreadsTable = &schema.Table{
		Name:       "threads",
		Columns:    ThreadsColumns,
		PrimaryKey: []*schema.Column{ThreadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "threads_projects_threads",
				Columns:    []*schema.Column{ThreadsColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "threads_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{ThreadsColumns[4]},
			},
			{
				Name:    "threads_by_thread_id",
				Unique:  true,
				Columns: []*schema.Column{ThreadsColumns[3]},
			},
		},
	}
	// TracesColumns holds the columns for the "traces" table.
	TracesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "trace_id", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt},
		{Name: "thread_id", Type: field.TypeInt, Nullable: true},
	}
	// TracesTable holds the schema information for the "traces" table.
	TracesTable = &schema.Table{
		Name:       "traces",
		Columns:    TracesColumns,
		PrimaryKey: []*schema.Column{TracesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "traces_projects_traces",
				Columns:    []*schema.Column{TracesColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "traces_threads_traces",
				Columns:    []*schema.Column{TracesColumns[5]},
				RefColumns: []*schema.Column{ThreadsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "traces_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[4]},
			},
			{
				Name:    "traces_by_trace_id",
				Unique:  true,
				Columns: []*schema.Column{TracesColumns[3]},
			},
			{
				Name:    "traces_by_thread_id",
				Unique:  false,
				Columns: []*schema.Column{TracesColumns[5]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "prompt_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "completion_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "prompt_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens_5m", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "prompt_write_cached_tokens_1h", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_audio_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_reasoning_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_accepted_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "completion_rejected_prediction_tokens", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "total_cost", Type: field.TypeFloat64, Nullable: true},
		{Name: "cost_items", Type: field.TypeJSON, Nullable: true},
		{Name: "cost_price_reference_id", Type: field.TypeString, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "project_id", Type: field.TypeInt, Default: 1},
		{Name: "request_id", Type: field.TypeInt},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_channels_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[22]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_projects_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[23]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_requests_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[24]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usage_logs_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[24]},
			},
			{
				Name:    "usage_logs_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_model_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[4], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_project_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[23], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[22], UsageLogsColumns[1]},
			},
			{
				Name:    "usage_logs_by_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[3], UsageLogsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"activated", "deactivated"}, Default: "activated"},
		{Name: "prefer_language", Type: field.TypeString, Default: "en"},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "mediumtext"}},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserProjectsColumns holds the columns for the "user_projects" table.
	UserProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "project_id", Type: field.TypeInt},
	}
	// UserProjectsTable holds the schema information for the "user_projects" table.
	UserProjectsTable = &schema.Table{
		Name:       "user_projects",
		Columns:    UserProjectsColumns,
		PrimaryKey: []*schema.Column{UserProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_projects_users_user",
				Columns:    []*schema.Column{UserProjectsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_projects_projects_project",
				Columns:    []*schema.Column{UserProjectsColumns[6]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_projects_by_user_id_project_id",
				Unique:  true,
				Columns: []*schema.Column{UserProjectsColumns[5], UserProjectsColumns[6]},
			},
			{
				Name:    "user_projects_by_project_id",
				Unique:  false,
				Columns: []*schema.Column{UserProjectsColumns[6]},
			},
		},
	}
	// UserQuotaColumns holds the columns for the "user_quota" table.
	UserQuotaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt, Unique: true},
		{Name: "quota", Type: field.TypeInt64, Default: 0},
		{Name: "used_quota", Type: field.TypeInt64, Default: 0},
		{Name: "group", Type: field.TypeString, Default: "default"},
		{Name: "aff_code", Type: field.TypeString, Nullable: true},
		{Name: "inviter_id", Type: field.TypeInt, Nullable: true},
		{Name: "notify", Type: field.TypeBool, Default: true},
		{Name: "quota_remind_threshold", Type: field.TypeInt64, Default: 100000},
	}
	// UserQuotaTable holds the schema information for the "user_quota" table.
	UserQuotaTable = &schema.Table{
		Name:       "user_quota",
		Columns:    UserQuotaColumns,
		PrimaryKey: []*schema.Column{UserQuotaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userquota_aff_code",
				Unique:  true,
				Columns: []*schema.Column{UserQuotaColumns[7]},
			},
			{
				Name:    "userquota_group",
				Unique:  false,
				Columns: []*schema.Column{UserQuotaColumns[6]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_users_user",
				Columns:    []*schema.Column{UserRolesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_roles_role",
				Columns:    []*schema.Column{UserRolesColumns[4]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_roles_by_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[3], UserRolesColumns[4]},
			},
			{
				Name:    "user_roles_by_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[4]},
			},
		},
	}
	// UserSubscriptionsColumns holds the columns for the "user_subscriptions" table.
	UserSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "plan_id", Type: field.TypeInt},
		{Name: "quota_remaining", Type: field.TypeInt64},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "expired", "cancelled"}, Default: "active"},
		{Name: "order_id", Type: field.TypeString, Nullable: true},
	}
	// UserSubscriptionsTable holds the schema information for the "user_subscriptions" table.
	UserSubscriptionsTable = &schema.Table{
		Name:       "user_subscriptions",
		Columns:    UserSubscriptionsColumns,
		PrimaryKey: []*schema.Column{UserSubscriptionsColumns[0]},
	}
	// ProjectPromptsColumns holds the columns for the "project_prompts" table.
	ProjectPromptsColumns = []*schema.Column{
		{Name: "project_id", Type: field.TypeInt},
		{Name: "prompt_id", Type: field.TypeInt},
	}
	// ProjectPromptsTable holds the schema information for the "project_prompts" table.
	ProjectPromptsTable = &schema.Table{
		Name:       "project_prompts",
		Columns:    ProjectPromptsColumns,
		PrimaryKey: []*schema.Column{ProjectPromptsColumns[0], ProjectPromptsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_prompts_project_id",
				Columns:    []*schema.Column{ProjectPromptsColumns[0]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_prompts_prompt_id",
				Columns:    []*schema.Column{ProjectPromptsColumns[1]},
				RefColumns: []*schema.Column{PromptsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		ChannelsTable,
		ChannelModelPricesTable,
		ChannelModelPriceVersionsTable,
		ChannelOverrideTemplatesTable,
		ChannelProbesTable,
		DataStoragesTable,
		ModelsTable,
		ProjectsTable,
		PromptsTable,
		ProviderQuotaStatusTable,
		QuotaTransactionsTable,
		RequestsTable,
		RequestExecutionsTable,
		RolesTable,
		SubscriptionPlansTable,
		SystemsTable,
		ThreadsTable,
		TracesTable,
		UsageLogsTable,
		UsersTable,
		UserProjectsTable,
		UserQuotaTable,
		UserRolesTable,
		UserSubscriptionsTable,
		ProjectPromptsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = ProjectsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	ChannelModelPricesTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelModelPriceVersionsTable.ForeignKeys[0].RefTable = ChannelModelPricesTable
	ChannelOverrideTemplatesTable.ForeignKeys[0].RefTable = UsersTable
	ChannelProbesTable.ForeignKeys[0].RefTable = ChannelsTable
	ProviderQuotaStatusTable.ForeignKeys[0].RefTable = ChannelsTable
	RequestsTable.ForeignKeys[0].RefTable = APIKeysTable
	RequestsTable.ForeignKeys[1].RefTable = ChannelsTable
	RequestsTable.ForeignKeys[2].RefTable = DataStoragesTable
	RequestsTable.ForeignKeys[3].RefTable = ProjectsTable
	RequestsTable.ForeignKeys[4].RefTable = TracesTable
	RequestExecutionsTable.ForeignKeys[0].RefTable = ChannelsTable
	RequestExecutionsTable.ForeignKeys[1].RefTable = DataStoragesTable
	RequestExecutionsTable.ForeignKeys[2].RefTable = RequestsTable
	RolesTable.ForeignKeys[0].RefTable = ProjectsTable
	ThreadsTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[0].RefTable = ProjectsTable
	TracesTable.ForeignKeys[1].RefTable = ThreadsTable
	UsageLogsTable.ForeignKeys[0].RefTable = ChannelsTable
	UsageLogsTable.ForeignKeys[1].RefTable = ProjectsTable
	UsageLogsTable.ForeignKeys[2].RefTable = RequestsTable
	UserProjectsTable.ForeignKeys[0].RefTable = UsersTable
	UserProjectsTable.ForeignKeys[1].RefTable = ProjectsTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
	ProjectPromptsTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectPromptsTable.ForeignKeys[1].RefTable = PromptsTable
}
