// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/quotatransaction"
)

// QuotaTransactionUpdate is the builder for updating QuotaTransaction entities.
type QuotaTransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *QuotaTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the QuotaTransactionUpdate builder.
func (_u *QuotaTransactionUpdate) Where(ps ...predicate.QuotaTransaction) *QuotaTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaTransactionUpdate) SetUpdatedAt(v time.Time) *QuotaTransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuotaTransactionUpdate) SetUserID(v int) *QuotaTransactionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableUserID(v *int) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *QuotaTransactionUpdate) AddUserID(v int) *QuotaTransactionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *QuotaTransactionUpdate) SetType(v quotatransaction.Type) *QuotaTransactionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableType(v *quotatransaction.Type) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *QuotaTransactionUpdate) SetAmount(v int64) *QuotaTransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableAmount(v *int64) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *QuotaTransactionUpdate) AddAmount(v int64) *QuotaTransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *QuotaTransactionUpdate) SetBalanceAfter(v int64) *QuotaTransactionUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableBalanceAfter(v *int64) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *QuotaTransactionUpdate) AddBalanceAfter(v int64) *QuotaTransactionUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *QuotaTransactionUpdate) SetDescription(v string) *QuotaTransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableDescription(v *string) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *QuotaTransactionUpdate) ClearDescription() *QuotaTransactionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *QuotaTransactionUpdate) SetOrderID(v string) *QuotaTransactionUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableOrderID(v *string) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *QuotaTransactionUpdate) ClearOrderID() *QuotaTransactionUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaTransactionUpdate) SetStatus(v quotatransaction.Status) *QuotaTransactionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaTransactionUpdate) SetNillableStatus(v *quotatransaction.Status) *QuotaTransactionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the QuotaTransactionMutation object of the builder.
func (_u *QuotaTransactionUpdate) Mutation() *QuotaTransactionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaTransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaTransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotatransaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaTransactionUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := quotatransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "QuotaTransaction.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotatransaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaTransaction.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *QuotaTransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *QuotaTransactionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *QuotaTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotatransaction.Table, quotatransaction.Columns, sqlgraph.NewFieldSpec(quotatransaction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotatransaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(quotatransaction.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(quotatransaction.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(quotatransaction.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(quotatransaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(quotatransaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(quotatransaction.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(quotatransaction.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(quotatransaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(quotatransaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(quotatransaction.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(quotatransaction.FieldOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotatransaction.FieldStatus, field.TypeEnum, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotatransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaTransactionUpdateOne is the builder for updating a single QuotaTransaction entity.
type QuotaTransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *QuotaTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaTransactionUpdateOne) SetUpdatedAt(v time.Time) *QuotaTransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuotaTransactionUpdateOne) SetUserID(v int) *QuotaTransactionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableUserID(v *int) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *QuotaTransactionUpdateOne) AddUserID(v int) *QuotaTransactionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *QuotaTransactionUpdateOne) SetType(v quotatransaction.Type) *QuotaTransactionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableType(v *quotatransaction.Type) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *QuotaTransactionUpdateOne) SetAmount(v int64) *QuotaTransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableAmount(v *int64) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *QuotaTransactionUpdateOne) AddAmount(v int64) *QuotaTransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *QuotaTransactionUpdateOne) SetBalanceAfter(v int64) *QuotaTransactionUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableBalanceAfter(v *int64) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *QuotaTransactionUpdateOne) AddBalanceAfter(v int64) *QuotaTransactionUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *QuotaTransactionUpdateOne) SetDescription(v string) *QuotaTransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableDescription(v *string) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *QuotaTransactionUpdateOne) ClearDescription() *QuotaTransactionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *QuotaTransactionUpdateOne) SetOrderID(v string) *QuotaTransactionUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableOrderID(v *string) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *QuotaTransactionUpdateOne) ClearOrderID() *QuotaTransactionUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaTransactionUpdateOne) SetStatus(v quotatransaction.Status) *QuotaTransactionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaTransactionUpdateOne) SetNillableStatus(v *quotatransaction.Status) *QuotaTransactionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the QuotaTransactionMutation object of the builder.
func (_u *QuotaTransactionUpdateOne) Mutation() *QuotaTransactionMutation {
	return _u.mutation
}

// Where appends a list predicates to the QuotaTransactionUpdate builder.
func (_u *QuotaTransactionUpdateOne) Where(ps ...predicate.QuotaTransaction) *QuotaTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaTransactionUpdateOne) Select(field string, fields ...string) *QuotaTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaTransaction entity.
func (_u *QuotaTransactionUpdateOne) Save(ctx context.Context) (*QuotaTransaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaTransactionUpdateOne) SaveX(ctx context.Context) *QuotaTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaTransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotatransaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaTransactionUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := quotatransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "QuotaTransaction.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotatransaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaTransaction.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *QuotaTransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *QuotaTransactionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *QuotaTransactionUpdateOne) sqlSave(ctx context.Context) (_node *QuotaTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotatransaction.Table, quotatransaction.Columns, sqlgraph.NewFieldSpec(quotatransaction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotatransaction.FieldID)
		for _, f := range fields {
			if !quotatransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotatransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotatransaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(quotatransaction.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(quotatransaction.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(quotatransaction.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(quotatransaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(quotatransaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(quotatransaction.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(quotatransaction.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(quotatransaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(quotatransaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(quotatransaction.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(quotatransaction.FieldOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotatransaction.FieldStatus, field.TypeEnum, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &QuotaTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotatransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
