// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/rechargeorder"
)

// RechargeOrderUpdate is the builder for updating RechargeOrder entities.
type RechargeOrderUpdate struct {
	config
	hooks     []Hook
	mutation  *RechargeOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RechargeOrderUpdate builder.
func (_u *RechargeOrderUpdate) Where(ps ...predicate.RechargeOrder) *RechargeOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeOrderUpdate) SetUpdatedAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *RechargeOrderUpdate) SetOrderID(v string) *RechargeOrderUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableOrderID(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeOrderUpdate) SetUserID(v int) *RechargeOrderUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableUserID(v *int) *RechargeOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RechargeOrderUpdate) AddUserID(v int) *RechargeOrderUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *RechargeOrderUpdate) SetType(v rechargeorder.Type) *RechargeOrderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableType(v *rechargeorder.Type) *RechargeOrderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeOrderUpdate) SetAmount(v int64) *RechargeOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableAmount(v *int64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeOrderUpdate) AddAmount(v int64) *RechargeOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeOrderUpdate) SetStatus(v rechargeorder.Status) *RechargeOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableStatus(v *rechargeorder.Status) *RechargeOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *RechargeOrderUpdate) SetPaymentMethod(v string) *RechargeOrderUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePaymentMethod(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (_u *RechargeOrderUpdate) ClearPaymentMethod() *RechargeOrderUpdate {
	_u.mutation.ClearPaymentMethod()
	return _u
}

// SetTradeID sets the "trade_id" field.
func (_u *RechargeOrderUpdate) SetTradeID(v string) *RechargeOrderUpdate {
	_u.mutation.SetTradeID(v)
	return _u
}

// SetNillableTradeID sets the "trade_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableTradeID(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetTradeID(*v)
	}
	return _u
}

// ClearTradeID clears the value of the "trade_id" field.
func (_u *RechargeOrderUpdate) ClearTradeID() *RechargeOrderUpdate {
	_u.mutation.ClearTradeID()
	return _u
}

// SetPaidAmount sets the "paid_amount" field.
func (_u *RechargeOrderUpdate) SetPaidAmount(v int64) *RechargeOrderUpdate {
	_u.mutation.ResetPaidAmount()
	_u.mutation.SetPaidAmount(v)
	return _u
}

// SetNillablePaidAmount sets the "paid_amount" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePaidAmount(v *int64) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPaidAmount(*v)
	}
	return _u
}

// AddPaidAmount adds value to the "paid_amount" field.
func (_u *RechargeOrderUpdate) AddPaidAmount(v int64) *RechargeOrderUpdate {
	_u.mutation.AddPaidAmount(v)
	return _u
}

// ClearPaidAmount clears the value of the "paid_amount" field.
func (_u *RechargeOrderUpdate) ClearPaidAmount() *RechargeOrderUpdate {
	_u.mutation.ClearPaidAmount()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *RechargeOrderUpdate) SetPaidAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePaidAt(v *time.Time) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *RechargeOrderUpdate) ClearPaidAt() *RechargeOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RechargeOrderUpdate) SetExpiresAt(v time.Time) *RechargeOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableExpiresAt(v *time.Time) *RechargeOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RechargeOrderUpdate) ClearExpiresAt() *RechargeOrderUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RechargeOrderUpdate) SetDescription(v string) *RechargeOrderUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillableDescription(v *string) *RechargeOrderUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RechargeOrderUpdate) ClearDescription() *RechargeOrderUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *RechargeOrderUpdate) SetPackageID(v int) *RechargeOrderUpdate {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *RechargeOrderUpdate) SetNillablePackageID(v *int) *RechargeOrderUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *RechargeOrderUpdate) AddPackageID(v int) *RechargeOrderUpdate {
	_u.mutation.AddPackageID(v)
	return _u
}

// ClearPackageID clears the value of the "package_id" field.
func (_u *RechargeOrderUpdate) ClearPackageID() *RechargeOrderUpdate {
	_u.mutation.ClearPackageID()
	return _u
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_u *RechargeOrderUpdate) Mutation() *RechargeOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargeOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargeOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeOrderUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := rechargeorder.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RechargeOrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RechargeOrderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RechargeOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeorder.Table, rechargeorder.Columns, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(rechargeorder.FieldOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(rechargeorder.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(rechargeorder.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(rechargeorder.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(rechargeorder.FieldPaymentMethod, field.TypeString, value)
	}
	if _u.mutation.PaymentMethodCleared() {
		_spec.ClearField(rechargeorder.FieldPaymentMethod, field.TypeString)
	}
	if value, ok := _u.mutation.TradeID(); ok {
		_spec.SetField(rechargeorder.FieldTradeID, field.TypeString, value)
	}
	if _u.mutation.TradeIDCleared() {
		_spec.ClearField(rechargeorder.FieldTradeID, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAmount(); ok {
		_spec.SetField(rechargeorder.FieldPaidAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaidAmount(); ok {
		_spec.AddField(rechargeorder.FieldPaidAmount, field.TypeInt64, value)
	}
	if _u.mutation.PaidAmountCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(rechargeorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(rechargeorder.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rechargeorder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rechargeorder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(rechargeorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(rechargeorder.FieldPackageID, field.TypeInt, value)
	}
	if _u.mutation.PackageIDCleared() {
		_spec.ClearField(rechargeorder.FieldPackageID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargeOrderUpdateOne is the builder for updating a single RechargeOrder entity.
type RechargeOrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RechargeOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeOrderUpdateOne) SetUpdatedAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *RechargeOrderUpdateOne) SetOrderID(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableOrderID(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RechargeOrderUpdateOne) SetUserID(v int) *RechargeOrderUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableUserID(v *int) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RechargeOrderUpdateOne) AddUserID(v int) *RechargeOrderUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *RechargeOrderUpdateOne) SetType(v rechargeorder.Type) *RechargeOrderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableType(v *rechargeorder.Type) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeOrderUpdateOne) SetAmount(v int64) *RechargeOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableAmount(v *int64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeOrderUpdateOne) AddAmount(v int64) *RechargeOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeOrderUpdateOne) SetStatus(v rechargeorder.Status) *RechargeOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableStatus(v *rechargeorder.Status) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *RechargeOrderUpdateOne) SetPaymentMethod(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePaymentMethod(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (_u *RechargeOrderUpdateOne) ClearPaymentMethod() *RechargeOrderUpdateOne {
	_u.mutation.ClearPaymentMethod()
	return _u
}

// SetTradeID sets the "trade_id" field.
func (_u *RechargeOrderUpdateOne) SetTradeID(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetTradeID(v)
	return _u
}

// SetNillableTradeID sets the "trade_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableTradeID(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetTradeID(*v)
	}
	return _u
}

// ClearTradeID clears the value of the "trade_id" field.
func (_u *RechargeOrderUpdateOne) ClearTradeID() *RechargeOrderUpdateOne {
	_u.mutation.ClearTradeID()
	return _u
}

// SetPaidAmount sets the "paid_amount" field.
func (_u *RechargeOrderUpdateOne) SetPaidAmount(v int64) *RechargeOrderUpdateOne {
	_u.mutation.ResetPaidAmount()
	_u.mutation.SetPaidAmount(v)
	return _u
}

// SetNillablePaidAmount sets the "paid_amount" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePaidAmount(v *int64) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPaidAmount(*v)
	}
	return _u
}

// AddPaidAmount adds value to the "paid_amount" field.
func (_u *RechargeOrderUpdateOne) AddPaidAmount(v int64) *RechargeOrderUpdateOne {
	_u.mutation.AddPaidAmount(v)
	return _u
}

// ClearPaidAmount clears the value of the "paid_amount" field.
func (_u *RechargeOrderUpdateOne) ClearPaidAmount() *RechargeOrderUpdateOne {
	_u.mutation.ClearPaidAmount()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *RechargeOrderUpdateOne) SetPaidAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePaidAt(v *time.Time) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *RechargeOrderUpdateOne) ClearPaidAt() *RechargeOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RechargeOrderUpdateOne) SetExpiresAt(v time.Time) *RechargeOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RechargeOrderUpdateOne) ClearExpiresAt() *RechargeOrderUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *RechargeOrderUpdateOne) SetDescription(v string) *RechargeOrderUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillableDescription(v *string) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RechargeOrderUpdateOne) ClearDescription() *RechargeOrderUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *RechargeOrderUpdateOne) SetPackageID(v int) *RechargeOrderUpdateOne {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *RechargeOrderUpdateOne) SetNillablePackageID(v *int) *RechargeOrderUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *RechargeOrderUpdateOne) AddPackageID(v int) *RechargeOrderUpdateOne {
	_u.mutation.AddPackageID(v)
	return _u
}

// ClearPackageID clears the value of the "package_id" field.
func (_u *RechargeOrderUpdateOne) ClearPackageID() *RechargeOrderUpdateOne {
	_u.mutation.ClearPackageID()
	return _u
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_u *RechargeOrderUpdateOne) Mutation() *RechargeOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the RechargeOrderUpdate builder.
func (_u *RechargeOrderUpdateOne) Where(ps ...predicate.RechargeOrder) *RechargeOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargeOrderUpdateOne) Select(field string, fields ...string) *RechargeOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargeOrder entity.
func (_u *RechargeOrderUpdateOne) Save(ctx context.Context) (*RechargeOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeOrderUpdateOne) SaveX(ctx context.Context) *RechargeOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargeOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargeOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargeorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeOrderUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := rechargeorder.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RechargeOrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RechargeOrderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RechargeOrderUpdateOne) sqlSave(ctx context.Context) (_node *RechargeOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeorder.Table, rechargeorder.Columns, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargeOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargeorder.FieldID)
		for _, f := range fields {
			if !rechargeorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargeorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(rechargeorder.FieldOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(rechargeorder.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(rechargeorder.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(rechargeorder.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeorder.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(rechargeorder.FieldPaymentMethod, field.TypeString, value)
	}
	if _u.mutation.PaymentMethodCleared() {
		_spec.ClearField(rechargeorder.FieldPaymentMethod, field.TypeString)
	}
	if value, ok := _u.mutation.TradeID(); ok {
		_spec.SetField(rechargeorder.FieldTradeID, field.TypeString, value)
	}
	if _u.mutation.TradeIDCleared() {
		_spec.ClearField(rechargeorder.FieldTradeID, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAmount(); ok {
		_spec.SetField(rechargeorder.FieldPaidAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaidAmount(); ok {
		_spec.AddField(rechargeorder.FieldPaidAmount, field.TypeInt64, value)
	}
	if _u.mutation.PaidAmountCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(rechargeorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(rechargeorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(rechargeorder.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rechargeorder.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rechargeorder.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(rechargeorder.FieldPackageID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(rechargeorder.FieldPackageID, field.TypeInt, value)
	}
	if _u.mutation.PackageIDCleared() {
		_spec.ClearField(rechargeorder.FieldPackageID, field.TypeInt)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RechargeOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
