// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/rechargeorder"
)

// RechargeOrderCreate is the builder for creating a RechargeOrder entity.
type RechargeOrderCreate struct {
	config
	mutation *RechargeOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeOrderCreate) SetCreatedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCreatedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargeOrderCreate) SetUpdatedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableUpdatedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *RechargeOrderCreate) SetOrderID(v string) *RechargeOrderCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RechargeOrderCreate) SetUserID(v int) *RechargeOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *RechargeOrderCreate) SetType(v rechargeorder.Type) *RechargeOrderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableType(v *rechargeorder.Type) *RechargeOrderCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RechargeOrderCreate) SetAmount(v int64) *RechargeOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RechargeOrderCreate) SetStatus(v rechargeorder.Status) *RechargeOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableStatus(v *rechargeorder.Status) *RechargeOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *RechargeOrderCreate) SetPaymentMethod(v string) *RechargeOrderCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePaymentMethod(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetPaymentMethod(*v)
	}
	return _c
}

// SetTradeID sets the "trade_id" field.
func (_c *RechargeOrderCreate) SetTradeID(v string) *RechargeOrderCreate {
	_c.mutation.SetTradeID(v)
	return _c
}

// SetNillableTradeID sets the "trade_id" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableTradeID(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetTradeID(*v)
	}
	return _c
}

// SetPaidAmount sets the "paid_amount" field.
func (_c *RechargeOrderCreate) SetPaidAmount(v int64) *RechargeOrderCreate {
	_c.mutation.SetPaidAmount(v)
	return _c
}

// SetNillablePaidAmount sets the "paid_amount" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePaidAmount(v *int64) *RechargeOrderCreate {
	if v != nil {
		_c.SetPaidAmount(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *RechargeOrderCreate) SetPaidAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePaidAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RechargeOrderCreate) SetExpiresAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableExpiresAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RechargeOrderCreate) SetDescription(v string) *RechargeOrderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableDescription(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPackageID sets the "package_id" field.
func (_c *RechargeOrderCreate) SetPackageID(v int) *RechargeOrderCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePackageID(v *int) *RechargeOrderCreate {
	if v != nil {
		_c.SetPackageID(*v)
	}
	return _c
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_c *RechargeOrderCreate) Mutation() *RechargeOrderMutation {
	return _c.mutation
}

// Save creates the RechargeOrder in the database.
func (_c *RechargeOrderCreate) Save(ctx context.Context) (*RechargeOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeOrderCreate) SaveX(ctx context.Context) *RechargeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargeorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rechargeorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := rechargeorder.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := rechargeorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargeOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "RechargeOrder.order_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RechargeOrder.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "RechargeOrder.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := rechargeorder.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RechargeOrder.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RechargeOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	return nil
}

func (_c *RechargeOrderCreate) sqlSave(ctx context.Context) (*RechargeOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeOrderCreate) createSpec() (*RechargeOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargeorder.Table, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargeorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(rechargeorder.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(rechargeorder.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(rechargeorder.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(rechargeorder.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.TradeID(); ok {
		_spec.SetField(rechargeorder.FieldTradeID, field.TypeString, value)
		_node.TradeID = &value
	}
	if value, ok := _c.mutation.PaidAmount(); ok {
		_spec.SetField(rechargeorder.FieldPaidAmount, field.TypeInt64, value)
		_node.PaidAmount = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(rechargeorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(rechargeorder.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(rechargeorder.FieldPackageID, field.TypeInt, value)
		_node.PackageID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeOrderCreate) OnConflict(opts ...sql.ConflictOption) *RechargeOrderUpsertOne {
	_c.conflict = opts
	return &RechargeOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeOrderCreate) OnConflictColumns(columns ...string) *RechargeOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeOrderUpsertOne{
		create: _c,
	}
}

type (
	// RechargeOrderUpsertOne is the builder for "upsert"-ing
	//  one RechargeOrder node.
	RechargeOrderUpsertOne struct {
		create *RechargeOrderCreate
	}

	// RechargeOrderUpsert is the "OnConflict" setter.
	RechargeOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsert) SetUpdatedAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateUpdatedAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldUpdatedAt)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *RechargeOrderUpsert) SetOrderID(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateOrderID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldOrderID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsert) SetUserID(v int) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateUserID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *RechargeOrderUpsert) AddUserID(v int) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldUserID, v)
	return u
}

// SetType sets the "type" field.
func (u *RechargeOrderUpsert) SetType(v rechargeorder.Type) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateType() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldType)
	return u
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsert) SetAmount(v int64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateAmount() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsert) AddAmount(v int64) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsert) SetStatus(v rechargeorder.Status) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateStatus() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldStatus)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *RechargeOrderUpsert) SetPaymentMethod(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaymentMethod() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaymentMethod)
	return u
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (u *RechargeOrderUpsert) ClearPaymentMethod() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPaymentMethod)
	return u
}

// SetTradeID sets the "trade_id" field.
func (u *RechargeOrderUpsert) SetTradeID(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldTradeID, v)
	return u
}

// UpdateTradeID sets the "trade_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateTradeID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldTradeID)
	return u
}

// ClearTradeID clears the value of the "trade_id" field.
func (u *RechargeOrderUpsert) ClearTradeID() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldTradeID)
	return u
}

// SetPaidAmount sets the "paid_amount" field.
func (u *RechargeOrderUpsert) SetPaidAmount(v int64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaidAmount, v)
	return u
}

// UpdatePaidAmount sets the "paid_amount" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaidAmount() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaidAmount)
	return u
}

// AddPaidAmount adds v to the "paid_amount" field.
func (u *RechargeOrderUpsert) AddPaidAmount(v int64) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldPaidAmount, v)
	return u
}

// ClearPaidAmount clears the value of the "paid_amount" field.
func (u *RechargeOrderUpsert) ClearPaidAmount() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPaidAmount)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsert) SetPaidAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaidAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsert) ClearPaidAt() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPaidAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *RechargeOrderUpsert) SetExpiresAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateExpiresAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RechargeOrderUpsert) ClearExpiresAt() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldExpiresAt)
	return u
}

// SetDescription sets the "description" field.
func (u *RechargeOrderUpsert) SetDescription(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateDescription() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *RechargeOrderUpsert) ClearDescription() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldDescription)
	return u
}

// SetPackageID sets the "package_id" field.
func (u *RechargeOrderUpsert) SetPackageID(v int) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPackageID, v)
	return u
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePackageID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPackageID)
	return u
}

// AddPackageID adds v to the "package_id" field.
func (u *RechargeOrderUpsert) AddPackageID(v int) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldPackageID, v)
	return u
}

// ClearPackageID clears the value of the "package_id" field.
func (u *RechargeOrderUpsert) ClearPackageID() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPackageID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeOrderUpsertOne) UpdateNewValues() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargeorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeOrderUpsertOne) Ignore() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeOrderUpsertOne) DoNothing() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeOrderCreate.OnConflict
// documentation for more info.
func (u *RechargeOrderUpsertOne) Update(set func(*RechargeOrderUpsert)) *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsertOne) SetUpdatedAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateUpdatedAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderID sets the "order_id" field.
func (u *RechargeOrderUpsertOne) SetOrderID(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateOrderID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsertOne) SetUserID(v int) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RechargeOrderUpsertOne) AddUserID(v int) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateUserID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *RechargeOrderUpsertOne) SetType(v rechargeorder.Type) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateType() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateType()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsertOne) SetAmount(v int64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsertOne) AddAmount(v int64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateAmount() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsertOne) SetStatus(v rechargeorder.Status) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateStatus() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *RechargeOrderUpsertOne) SetPaymentMethod(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaymentMethod() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (u *RechargeOrderUpsertOne) ClearPaymentMethod() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaymentMethod()
	})
}

// SetTradeID sets the "trade_id" field.
func (u *RechargeOrderUpsertOne) SetTradeID(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetTradeID(v)
	})
}

// UpdateTradeID sets the "trade_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateTradeID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateTradeID()
	})
}

// ClearTradeID clears the value of the "trade_id" field.
func (u *RechargeOrderUpsertOne) ClearTradeID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearTradeID()
	})
}

// SetPaidAmount sets the "paid_amount" field.
func (u *RechargeOrderUpsertOne) SetPaidAmount(v int64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAmount(v)
	})
}

// AddPaidAmount adds v to the "paid_amount" field.
func (u *RechargeOrderUpsertOne) AddPaidAmount(v int64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddPaidAmount(v)
	})
}

// UpdatePaidAmount sets the "paid_amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaidAmount() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAmount()
	})
}

// ClearPaidAmount clears the value of the "paid_amount" field.
func (u *RechargeOrderUpsertOne) ClearPaidAmount() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAmount()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsertOne) SetPaidAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaidAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsertOne) ClearPaidAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RechargeOrderUpsertOne) SetExpiresAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateExpiresAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RechargeOrderUpsertOne) ClearExpiresAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetDescription sets the "description" field.
func (u *RechargeOrderUpsertOne) SetDescription(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateDescription() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RechargeOrderUpsertOne) ClearDescription() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearDescription()
	})
}

// SetPackageID sets the "package_id" field.
func (u *RechargeOrderUpsertOne) SetPackageID(v int) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *RechargeOrderUpsertOne) AddPackageID(v int) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePackageID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePackageID()
	})
}

// ClearPackageID clears the value of the "package_id" field.
func (u *RechargeOrderUpsertOne) ClearPackageID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPackageID()
	})
}

// Exec executes the query.
func (u *RechargeOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeOrderUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeOrderUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeOrderCreateBulk is the builder for creating many RechargeOrder entities in bulk.
type RechargeOrderCreateBulk struct {
	config
	err      error
	builders []*RechargeOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeOrder entities in the database.
func (_c *RechargeOrderCreateBulk) Save(ctx context.Context) ([]*RechargeOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeOrderCreateBulk) SaveX(ctx context.Context) []*RechargeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeOrderUpsertBulk {
	_c.conflict = opts
	return &RechargeOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeOrderCreateBulk) OnConflictColumns(columns ...string) *RechargeOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeOrderUpsertBulk{
		create: _c,
	}
}

// RechargeOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeOrder nodes.
type RechargeOrderUpsertBulk struct {
	create *RechargeOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeOrderUpsertBulk) UpdateNewValues() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargeorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeOrderUpsertBulk) Ignore() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeOrderUpsertBulk) DoNothing() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeOrderCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeOrderUpsertBulk) Update(set func(*RechargeOrderUpsert)) *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsertBulk) SetUpdatedAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateUpdatedAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderID sets the "order_id" field.
func (u *RechargeOrderUpsertBulk) SetOrderID(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateOrderID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsertBulk) SetUserID(v int) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RechargeOrderUpsertBulk) AddUserID(v int) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateUserID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *RechargeOrderUpsertBulk) SetType(v rechargeorder.Type) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateType() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateType()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsertBulk) SetAmount(v int64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsertBulk) AddAmount(v int64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateAmount() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsertBulk) SetStatus(v rechargeorder.Status) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateStatus() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *RechargeOrderUpsertBulk) SetPaymentMethod(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaymentMethod() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// ClearPaymentMethod clears the value of the "payment_method" field.
func (u *RechargeOrderUpsertBulk) ClearPaymentMethod() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaymentMethod()
	})
}

// SetTradeID sets the "trade_id" field.
func (u *RechargeOrderUpsertBulk) SetTradeID(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetTradeID(v)
	})
}

// UpdateTradeID sets the "trade_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateTradeID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateTradeID()
	})
}

// ClearTradeID clears the value of the "trade_id" field.
func (u *RechargeOrderUpsertBulk) ClearTradeID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearTradeID()
	})
}

// SetPaidAmount sets the "paid_amount" field.
func (u *RechargeOrderUpsertBulk) SetPaidAmount(v int64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAmount(v)
	})
}

// AddPaidAmount adds v to the "paid_amount" field.
func (u *RechargeOrderUpsertBulk) AddPaidAmount(v int64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddPaidAmount(v)
	})
}

// UpdatePaidAmount sets the "paid_amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaidAmount() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAmount()
	})
}

// ClearPaidAmount clears the value of the "paid_amount" field.
func (u *RechargeOrderUpsertBulk) ClearPaidAmount() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAmount()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsertBulk) SetPaidAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaidAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsertBulk) ClearPaidAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RechargeOrderUpsertBulk) SetExpiresAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateExpiresAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RechargeOrderUpsertBulk) ClearExpiresAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// SetDescription sets the "description" field.
func (u *RechargeOrderUpsertBulk) SetDescription(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateDescription() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RechargeOrderUpsertBulk) ClearDescription() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearDescription()
	})
}

// SetPackageID sets the "package_id" field.
func (u *RechargeOrderUpsertBulk) SetPackageID(v int) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *RechargeOrderUpsertBulk) AddPackageID(v int) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePackageID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePackageID()
	})
}

// ClearPackageID clears the value of the "package_id" field.
func (u *RechargeOrderUpsertBulk) ClearPackageID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPackageID()
	})
}

// Exec executes the query.
func (u *RechargeOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
