// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/subscriptionplan"
)

// SubscriptionPlanUpdate is the builder for updating SubscriptionPlan entities.
type SubscriptionPlanUpdate struct {
	config
	hooks     []Hook
	mutation  *SubscriptionPlanMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdate) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPlanUpdate) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionPlanUpdate) SetDeletedAt(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDeletedAt(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *SubscriptionPlanUpdate) AddDeletedAt(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionPlanUpdate) SetName(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableName(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SubscriptionPlanUpdate) SetDisplayName(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDisplayName(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdate) SetPrice(v int64) *SubscriptionPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillablePrice(v *int64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdate) AddPrice(v int64) *SubscriptionPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionPlanUpdate) SetCurrency(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableCurrency(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetQuota sets the "quota" field.
func (_u *SubscriptionPlanUpdate) SetQuota(v int64) *SubscriptionPlanUpdate {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableQuota(v *int64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *SubscriptionPlanUpdate) AddQuota(v int64) *SubscriptionPlanUpdate {
	_u.mutation.AddQuota(v)
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *SubscriptionPlanUpdate) SetDurationDays(v int64) *SubscriptionPlanUpdate {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDurationDays(v *int64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *SubscriptionPlanUpdate) AddDurationDays(v int64) *SubscriptionPlanUpdate {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *SubscriptionPlanUpdate) SetFeatures(v []string) *SubscriptionPlanUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// AppendFeatures appends value to the "features" field.
func (_u *SubscriptionPlanUpdate) AppendFeatures(v []string) *SubscriptionPlanUpdate {
	_u.mutation.AppendFeatures(v)
	return _u
}

// ClearFeatures clears the value of the "features" field.
func (_u *SubscriptionPlanUpdate) ClearFeatures() *SubscriptionPlanUpdate {
	_u.mutation.ClearFeatures()
	return _u
}

// SetIsPopular sets the "is_popular" field.
func (_u *SubscriptionPlanUpdate) SetIsPopular(v bool) *SubscriptionPlanUpdate {
	_u.mutation.SetIsPopular(v)
	return _u
}

// SetNillableIsPopular sets the "is_popular" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableIsPopular(v *bool) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetIsPopular(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionPlanUpdate) SetSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableSortOrder(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionPlanUpdate) AddSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPlanUpdate) SetStatus(v bool) *SubscriptionPlanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableStatus(v *bool) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdate) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPlanUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SubscriptionPlanUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubscriptionPlanUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SubscriptionPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplan.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(subscriptionplan.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(subscriptionplan.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionplan.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(subscriptionplan.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(subscriptionplan.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(subscriptionplan.FieldDurationDays, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(subscriptionplan.FieldDurationDays, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(subscriptionplan.FieldFeatures, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFeatures(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptionplan.FieldFeatures, value)
		})
	}
	if _u.mutation.FeaturesCleared() {
		_spec.ClearField(subscriptionplan.FieldFeatures, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsPopular(); ok {
		_spec.SetField(subscriptionplan.FieldIsPopular, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionplan.FieldStatus, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPlanUpdateOne is the builder for updating a single SubscriptionPlan entity.
type SubscriptionPlanUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SubscriptionPlanMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPlanUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionPlanUpdateOne) SetDeletedAt(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDeletedAt(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *SubscriptionPlanUpdateOne) AddDeletedAt(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionPlanUpdateOne) SetName(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableName(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SubscriptionPlanUpdateOne) SetDisplayName(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDisplayName(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdateOne) SetPrice(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillablePrice(v *int64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdateOne) AddPrice(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionPlanUpdateOne) SetCurrency(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableCurrency(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetQuota sets the "quota" field.
func (_u *SubscriptionPlanUpdateOne) SetQuota(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableQuota(v *int64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *SubscriptionPlanUpdateOne) AddQuota(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddQuota(v)
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *SubscriptionPlanUpdateOne) SetDurationDays(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDurationDays(v *int64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *SubscriptionPlanUpdateOne) AddDurationDays(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *SubscriptionPlanUpdateOne) SetFeatures(v []string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// AppendFeatures appends value to the "features" field.
func (_u *SubscriptionPlanUpdateOne) AppendFeatures(v []string) *SubscriptionPlanUpdateOne {
	_u.mutation.AppendFeatures(v)
	return _u
}

// ClearFeatures clears the value of the "features" field.
func (_u *SubscriptionPlanUpdateOne) ClearFeatures() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearFeatures()
	return _u
}

// SetIsPopular sets the "is_popular" field.
func (_u *SubscriptionPlanUpdateOne) SetIsPopular(v bool) *SubscriptionPlanUpdateOne {
	_u.mutation.SetIsPopular(v)
	return _u
}

// SetNillableIsPopular sets the "is_popular" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableIsPopular(v *bool) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetIsPopular(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionPlanUpdateOne) SetSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableSortOrder(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionPlanUpdateOne) AddSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPlanUpdateOne) SetStatus(v bool) *SubscriptionPlanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableStatus(v *bool) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdateOne) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdateOne) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPlanUpdateOne) Select(field string, fields ...string) *SubscriptionPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPlan entity.
func (_u *SubscriptionPlanUpdateOne) Save(ctx context.Context) (*SubscriptionPlan, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) SaveX(ctx context.Context) *SubscriptionPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SubscriptionPlanUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubscriptionPlanUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SubscriptionPlanUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPlan, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionplan.FieldID)
		for _, f := range fields {
			if !subscriptionplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplan.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(subscriptionplan.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(subscriptionplan.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionplan.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(subscriptionplan.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(subscriptionplan.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(subscriptionplan.FieldDurationDays, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(subscriptionplan.FieldDurationDays, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(subscriptionplan.FieldFeatures, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFeatures(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptionplan.FieldFeatures, value)
		})
	}
	if _u.mutation.FeaturesCleared() {
		_spec.ClearField(subscriptionplan.FieldFeatures, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsPopular(); ok {
		_spec.SetField(subscriptionplan.FieldIsPopular, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionplan.FieldStatus, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SubscriptionPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
