// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/subscriptionplan"
)

// SubscriptionPlanCreate is the builder for creating a SubscriptionPlan entity.
type SubscriptionPlanCreate struct {
	config
	mutation *SubscriptionPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPlanCreate) SetCreatedAt(v time.Time) *SubscriptionPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionPlanCreate) SetUpdatedAt(v time.Time) *SubscriptionPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubscriptionPlanCreate) SetDeletedAt(v int) *SubscriptionPlanCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableDeletedAt(v *int) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SubscriptionPlanCreate) SetName(v string) *SubscriptionPlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *SubscriptionPlanCreate) SetDisplayName(v string) *SubscriptionPlanCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *SubscriptionPlanCreate) SetPrice(v int64) *SubscriptionPlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *SubscriptionPlanCreate) SetCurrency(v string) *SubscriptionPlanCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableCurrency(v *string) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetQuota sets the "quota" field.
func (_c *SubscriptionPlanCreate) SetQuota(v int64) *SubscriptionPlanCreate {
	_c.mutation.SetQuota(v)
	return _c
}

// SetDurationDays sets the "duration_days" field.
func (_c *SubscriptionPlanCreate) SetDurationDays(v int64) *SubscriptionPlanCreate {
	_c.mutation.SetDurationDays(v)
	return _c
}

// SetFeatures sets the "features" field.
func (_c *SubscriptionPlanCreate) SetFeatures(v []string) *SubscriptionPlanCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetIsPopular sets the "is_popular" field.
func (_c *SubscriptionPlanCreate) SetIsPopular(v bool) *SubscriptionPlanCreate {
	_c.mutation.SetIsPopular(v)
	return _c
}

// SetNillableIsPopular sets the "is_popular" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableIsPopular(v *bool) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetIsPopular(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SubscriptionPlanCreate) SetSortOrder(v int) *SubscriptionPlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableSortOrder(v *int) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionPlanCreate) SetStatus(v bool) *SubscriptionPlanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionPlanCreate) SetNillableStatus(v *bool) *SubscriptionPlanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_c *SubscriptionPlanCreate) Mutation() *SubscriptionPlanMutation {
	return _c.mutation
}

// Save creates the SubscriptionPlan in the database.
func (_c *SubscriptionPlanCreate) Save(ctx context.Context) (*SubscriptionPlan, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPlanCreate) SaveX(ctx context.Context) *SubscriptionPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPlanCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if subscriptionplan.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if subscriptionplan.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionplan.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := subscriptionplan.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := subscriptionplan.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.IsPopular(); !ok {
		v := subscriptionplan.DefaultIsPopular
		_c.mutation.SetIsPopular(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := subscriptionplan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionplan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPlanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionPlan.updated_at"`)}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "SubscriptionPlan.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SubscriptionPlan.name"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "SubscriptionPlan.display_name"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "SubscriptionPlan.price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "SubscriptionPlan.currency"`)}
	}
	if _, ok := _c.mutation.Quota(); !ok {
		return &ValidationError{Name: "quota", err: errors.New(`ent: missing required field "SubscriptionPlan.quota"`)}
	}
	if _, ok := _c.mutation.DurationDays(); !ok {
		return &ValidationError{Name: "duration_days", err: errors.New(`ent: missing required field "SubscriptionPlan.duration_days"`)}
	}
	if _, ok := _c.mutation.IsPopular(); !ok {
		return &ValidationError{Name: "is_popular", err: errors.New(`ent: missing required field "SubscriptionPlan.is_popular"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SubscriptionPlan.sort_order"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionPlan.status"`)}
	}
	return nil
}

func (_c *SubscriptionPlanCreate) sqlSave(ctx context.Context) (*SubscriptionPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPlanCreate) createSpec() (*SubscriptionPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionplan.Table, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplan.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(subscriptionplan.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeInt64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(subscriptionplan.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Quota(); ok {
		_spec.SetField(subscriptionplan.FieldQuota, field.TypeInt64, value)
		_node.Quota = value
	}
	if value, ok := _c.mutation.DurationDays(); ok {
		_spec.SetField(subscriptionplan.FieldDurationDays, field.TypeInt64, value)
		_node.DurationDays = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(subscriptionplan.FieldFeatures, field.TypeJSON, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.IsPopular(); ok {
		_spec.SetField(subscriptionplan.FieldIsPopular, field.TypeBool, value)
		_node.IsPopular = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionplan.FieldStatus, field.TypeBool, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanUpsertOne {
	_c.conflict = opts
	return &SubscriptionPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanCreate) OnConflictColumns(columns ...string) *SubscriptionPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPlanUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPlan node.
	SubscriptionPlanUpsertOne struct {
		create *SubscriptionPlanCreate
	}

	// SubscriptionPlanUpsert is the "OnConflict" setter.
	SubscriptionPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanUpsert) SetUpdatedAt(v time.Time) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateUpdatedAt() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanUpsert) SetDeletedAt(v int) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDeletedAt() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SubscriptionPlanUpsert) AddDeletedAt(v int) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *SubscriptionPlanUpsert) SetName(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateName() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldName)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *SubscriptionPlanUpsert) SetDisplayName(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDisplayName() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDisplayName)
	return u
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanUpsert) SetPrice(v int64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdatePrice() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanUpsert) AddPrice(v int64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldPrice, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionPlanUpsert) SetCurrency(v string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateCurrency() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldCurrency)
	return u
}

// SetQuota sets the "quota" field.
func (u *SubscriptionPlanUpsert) SetQuota(v int64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldQuota, v)
	return u
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateQuota() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldQuota)
	return u
}

// AddQuota adds v to the "quota" field.
func (u *SubscriptionPlanUpsert) AddQuota(v int64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldQuota, v)
	return u
}

// SetDurationDays sets the "duration_days" field.
func (u *SubscriptionPlanUpsert) SetDurationDays(v int64) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldDurationDays, v)
	return u
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateDurationDays() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldDurationDays)
	return u
}

// AddDurationDays adds v to the "duration_days" field.
func (u *SubscriptionPlanUpsert) AddDurationDays(v int64) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldDurationDays, v)
	return u
}

// SetFeatures sets the "features" field.
func (u *SubscriptionPlanUpsert) SetFeatures(v []string) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateFeatures() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldFeatures)
	return u
}

// ClearFeatures clears the value of the "features" field.
func (u *SubscriptionPlanUpsert) ClearFeatures() *SubscriptionPlanUpsert {
	u.SetNull(subscriptionplan.FieldFeatures)
	return u
}

// SetIsPopular sets the "is_popular" field.
func (u *SubscriptionPlanUpsert) SetIsPopular(v bool) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldIsPopular, v)
	return u
}

// UpdateIsPopular sets the "is_popular" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateIsPopular() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldIsPopular)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionPlanUpsert) SetSortOrder(v int) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateSortOrder() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionPlanUpsert) AddSortOrder(v int) *SubscriptionPlanUpsert {
	u.Add(subscriptionplan.FieldSortOrder, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionPlanUpsert) SetStatus(v bool) *SubscriptionPlanUpsert {
	u.Set(subscriptionplan.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPlanUpsert) UpdateStatus() *SubscriptionPlanUpsert {
	u.SetExcluded(subscriptionplan.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanUpsertOne) UpdateNewValues() *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPlanUpsertOne) Ignore() *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanUpsertOne) DoNothing() *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPlanUpsertOne) Update(set func(*SubscriptionPlanUpsert)) *SubscriptionPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateUpdatedAt() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanUpsertOne) SetDeletedAt(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SubscriptionPlanUpsertOne) AddDeletedAt(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDeletedAt() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *SubscriptionPlanUpsertOne) SetName(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateName() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *SubscriptionPlanUpsertOne) SetDisplayName(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDisplayName() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDisplayName()
	})
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanUpsertOne) SetPrice(v int64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanUpsertOne) AddPrice(v int64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdatePrice() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdatePrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionPlanUpsertOne) SetCurrency(v string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateCurrency() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateCurrency()
	})
}

// SetQuota sets the "quota" field.
func (u *SubscriptionPlanUpsertOne) SetQuota(v int64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetQuota(v)
	})
}

// AddQuota adds v to the "quota" field.
func (u *SubscriptionPlanUpsertOne) AddQuota(v int64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddQuota(v)
	})
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateQuota() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateQuota()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *SubscriptionPlanUpsertOne) SetDurationDays(v int64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *SubscriptionPlanUpsertOne) AddDurationDays(v int64) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateDurationDays() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDurationDays()
	})
}

// SetFeatures sets the "features" field.
func (u *SubscriptionPlanUpsertOne) SetFeatures(v []string) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateFeatures() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *SubscriptionPlanUpsertOne) ClearFeatures() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearFeatures()
	})
}

// SetIsPopular sets the "is_popular" field.
func (u *SubscriptionPlanUpsertOne) SetIsPopular(v bool) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetIsPopular(v)
	})
}

// UpdateIsPopular sets the "is_popular" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateIsPopular() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateIsPopular()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionPlanUpsertOne) SetSortOrder(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionPlanUpsertOne) AddSortOrder(v int) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateSortOrder() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionPlanUpsertOne) SetStatus(v bool) *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertOne) UpdateStatus() *SubscriptionPlanUpsertOne {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionPlanUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionPlanUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionPlanCreateBulk is the builder for creating many SubscriptionPlan entities in bulk.
type SubscriptionPlanCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPlan entities in the database.
func (_c *SubscriptionPlanCreateBulk) Save(ctx context.Context) ([]*SubscriptionPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPlanCreateBulk) SaveX(ctx context.Context) []*SubscriptionPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanUpsertBulk{
		create: _c,
	}
}

// SubscriptionPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPlan nodes.
type SubscriptionPlanUpsertBulk struct {
	create *SubscriptionPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanUpsertBulk) UpdateNewValues() *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPlanUpsertBulk) Ignore() *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanUpsertBulk) DoNothing() *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPlanUpsertBulk) Update(set func(*SubscriptionPlanUpsert)) *SubscriptionPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateUpdatedAt() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanUpsertBulk) SetDeletedAt(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SubscriptionPlanUpsertBulk) AddDeletedAt(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDeletedAt() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *SubscriptionPlanUpsertBulk) SetName(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateName() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *SubscriptionPlanUpsertBulk) SetDisplayName(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDisplayName() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDisplayName()
	})
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanUpsertBulk) SetPrice(v int64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanUpsertBulk) AddPrice(v int64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdatePrice() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdatePrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionPlanUpsertBulk) SetCurrency(v string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateCurrency() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateCurrency()
	})
}

// SetQuota sets the "quota" field.
func (u *SubscriptionPlanUpsertBulk) SetQuota(v int64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetQuota(v)
	})
}

// AddQuota adds v to the "quota" field.
func (u *SubscriptionPlanUpsertBulk) AddQuota(v int64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddQuota(v)
	})
}

// UpdateQuota sets the "quota" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateQuota() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateQuota()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *SubscriptionPlanUpsertBulk) SetDurationDays(v int64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *SubscriptionPlanUpsertBulk) AddDurationDays(v int64) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateDurationDays() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateDurationDays()
	})
}

// SetFeatures sets the "features" field.
func (u *SubscriptionPlanUpsertBulk) SetFeatures(v []string) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateFeatures() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *SubscriptionPlanUpsertBulk) ClearFeatures() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.ClearFeatures()
	})
}

// SetIsPopular sets the "is_popular" field.
func (u *SubscriptionPlanUpsertBulk) SetIsPopular(v bool) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetIsPopular(v)
	})
}

// UpdateIsPopular sets the "is_popular" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateIsPopular() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateIsPopular()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubscriptionPlanUpsertBulk) SetSortOrder(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubscriptionPlanUpsertBulk) AddSortOrder(v int) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateSortOrder() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionPlanUpsertBulk) SetStatus(v bool) *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPlanUpsertBulk) UpdateStatus() *SubscriptionPlanUpsertBulk {
	return u.Update(func(s *SubscriptionPlanUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
