// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/userquota"
)

// UserQuota is the model entity for the UserQuota schema.
type UserQuota struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 关联的用户ID
	UserID int `json:"user_id,omitempty"`
	// 账户余额（单位：分）
	Quota int64 `json:"quota,omitempty"`
	// 已使用额度（单位：分）
	UsedQuota int64 `json:"used_quota,omitempty"`
	// 用户分组/等级
	Group string `json:"group,omitempty"`
	// 邀请码
	AffCode *string `json:"aff_code,omitempty"`
	// 邀请人ID
	InviterID *int `json:"inviter_id,omitempty"`
	// 是否接收余额提醒
	Notify bool `json:"notify,omitempty"`
	// 余额提醒阈值（单位：分，默认20元）
	QuotaRemindThreshold int64 `json:"quota_remind_threshold,omitempty"`
	selectValues         sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserQuota) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userquota.FieldNotify:
			values[i] = new(sql.NullBool)
		case userquota.FieldID, userquota.FieldUserID, userquota.FieldQuota, userquota.FieldUsedQuota, userquota.FieldInviterID, userquota.FieldQuotaRemindThreshold:
			values[i] = new(sql.NullInt64)
		case userquota.FieldGroup, userquota.FieldAffCode:
			values[i] = new(sql.NullString)
		case userquota.FieldCreatedAt, userquota.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserQuota fields.
func (_m *UserQuota) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userquota.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userquota.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userquota.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userquota.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case userquota.FieldQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota", values[i])
			} else if value.Valid {
				_m.Quota = value.Int64
			}
		case userquota.FieldUsedQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_quota", values[i])
			} else if value.Valid {
				_m.UsedQuota = value.Int64
			}
		case userquota.FieldGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group", values[i])
			} else if value.Valid {
				_m.Group = value.String
			}
		case userquota.FieldAffCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aff_code", values[i])
			} else if value.Valid {
				_m.AffCode = new(string)
				*_m.AffCode = value.String
			}
		case userquota.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				_m.InviterID = new(int)
				*_m.InviterID = int(value.Int64)
			}
		case userquota.FieldNotify:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field notify", values[i])
			} else if value.Valid {
				_m.Notify = value.Bool
			}
		case userquota.FieldQuotaRemindThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_remind_threshold", values[i])
			} else if value.Valid {
				_m.QuotaRemindThreshold = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserQuota.
// This includes values selected through modifiers, order, etc.
func (_m *UserQuota) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserQuota.
// Note that you need to call UserQuota.Unwrap() before calling this method if this UserQuota
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserQuota) Update() *UserQuotaUpdateOne {
	return NewUserQuotaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserQuota entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserQuota) Unwrap() *UserQuota {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserQuota is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserQuota) String() string {
	var builder strings.Builder
	builder.WriteString("UserQuota(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quota))
	builder.WriteString(", ")
	builder.WriteString("used_quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedQuota))
	builder.WriteString(", ")
	builder.WriteString("group=")
	builder.WriteString(_m.Group)
	builder.WriteString(", ")
	if v := _m.AffCode; v != nil {
		builder.WriteString("aff_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InviterID; v != nil {
		builder.WriteString("inviter_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notify=")
	builder.WriteString(fmt.Sprintf("%v", _m.Notify))
	builder.WriteString(", ")
	builder.WriteString("quota_remind_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaRemindThreshold))
	builder.WriteByte(')')
	return builder.String()
}

// UserQuotaSlice is a parsable slice of UserQuota.
type UserQuotaSlice []*UserQuota
