// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/usersubscription"
)

// UserSubscriptionUpdate is the builder for updating UserSubscription entities.
type UserSubscriptionUpdate struct {
	config
	hooks     []Hook
	mutation  *UserSubscriptionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserSubscriptionUpdate builder.
func (_u *UserSubscriptionUpdate) Where(ps ...predicate.UserSubscription) *UserSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscriptionUpdate) SetUpdatedAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSubscriptionUpdate) SetUserID(v int) *UserSubscriptionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableUserID(v *int) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserSubscriptionUpdate) AddUserID(v int) *UserSubscriptionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserSubscriptionUpdate) SetPlanID(v int) *UserSubscriptionUpdate {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillablePlanID(v *int) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *UserSubscriptionUpdate) AddPlanID(v int) *UserSubscriptionUpdate {
	_u.mutation.AddPlanID(v)
	return _u
}

// SetQuotaRemaining sets the "quota_remaining" field.
func (_u *UserSubscriptionUpdate) SetQuotaRemaining(v int64) *UserSubscriptionUpdate {
	_u.mutation.ResetQuotaRemaining()
	_u.mutation.SetQuotaRemaining(v)
	return _u
}

// SetNillableQuotaRemaining sets the "quota_remaining" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableQuotaRemaining(v *int64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetQuotaRemaining(*v)
	}
	return _u
}

// AddQuotaRemaining adds value to the "quota_remaining" field.
func (_u *UserSubscriptionUpdate) AddQuotaRemaining(v int64) *UserSubscriptionUpdate {
	_u.mutation.AddQuotaRemaining(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserSubscriptionUpdate) SetExpiresAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableExpiresAt(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscriptionUpdate) SetStatus(v usersubscription.Status) *UserSubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStatus(v *usersubscription.Status) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *UserSubscriptionUpdate) SetOrderID(v string) *UserSubscriptionUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableOrderID(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *UserSubscriptionUpdate) ClearOrderID() *UserSubscriptionUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (_u *UserSubscriptionUpdate) Mutation() *UserSubscriptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usersubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserSubscriptionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserSubscriptionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscription.Table, usersubscription.Columns, sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usersubscription.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usersubscription.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(usersubscription.FieldPlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(usersubscription.FieldPlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaRemaining(); ok {
		_spec.SetField(usersubscription.FieldQuotaRemaining, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRemaining(); ok {
		_spec.AddField(usersubscription.FieldQuotaRemaining, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(usersubscription.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(usersubscription.FieldOrderID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSubscriptionUpdateOne is the builder for updating a single UserSubscription entity.
type UserSubscriptionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserSubscriptionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSubscriptionUpdateOne) SetUserID(v int) *UserSubscriptionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableUserID(v *int) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserSubscriptionUpdateOne) AddUserID(v int) *UserSubscriptionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserSubscriptionUpdateOne) SetPlanID(v int) *UserSubscriptionUpdateOne {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillablePlanID(v *int) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *UserSubscriptionUpdateOne) AddPlanID(v int) *UserSubscriptionUpdateOne {
	_u.mutation.AddPlanID(v)
	return _u
}

// SetQuotaRemaining sets the "quota_remaining" field.
func (_u *UserSubscriptionUpdateOne) SetQuotaRemaining(v int64) *UserSubscriptionUpdateOne {
	_u.mutation.ResetQuotaRemaining()
	_u.mutation.SetQuotaRemaining(v)
	return _u
}

// SetNillableQuotaRemaining sets the "quota_remaining" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableQuotaRemaining(v *int64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetQuotaRemaining(*v)
	}
	return _u
}

// AddQuotaRemaining adds value to the "quota_remaining" field.
func (_u *UserSubscriptionUpdateOne) AddQuotaRemaining(v int64) *UserSubscriptionUpdateOne {
	_u.mutation.AddQuotaRemaining(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserSubscriptionUpdateOne) SetExpiresAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableExpiresAt(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscriptionUpdateOne) SetStatus(v usersubscription.Status) *UserSubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStatus(v *usersubscription.Status) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *UserSubscriptionUpdateOne) SetOrderID(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableOrderID(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *UserSubscriptionUpdateOne) ClearOrderID() *UserSubscriptionUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (_u *UserSubscriptionUpdateOne) Mutation() *UserSubscriptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserSubscriptionUpdate builder.
func (_u *UserSubscriptionUpdateOne) Where(ps ...predicate.UserSubscription) *UserSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSubscriptionUpdateOne) Select(field string, fields ...string) *UserSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSubscription entity.
func (_u *UserSubscriptionUpdateOne) Save(ctx context.Context) (*UserSubscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionUpdateOne) SaveX(ctx context.Context) *UserSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usersubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserSubscriptionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserSubscriptionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *UserSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscription.Table, usersubscription.Columns, sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscription.FieldID)
		for _, f := range fields {
			if !usersubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usersubscription.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usersubscription.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(usersubscription.FieldPlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(usersubscription.FieldPlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaRemaining(); ok {
		_spec.SetField(usersubscription.FieldQuotaRemaining, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRemaining(); ok {
		_spec.AddField(usersubscription.FieldQuotaRemaining, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(usersubscription.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(usersubscription.FieldOrderID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
