// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/userquota"
)

// UserQuotaUpdate is the builder for updating UserQuota entities.
type UserQuotaUpdate struct {
	config
	hooks     []Hook
	mutation  *UserQuotaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserQuotaUpdate builder.
func (_u *UserQuotaUpdate) Where(ps ...predicate.UserQuota) *UserQuotaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserQuotaUpdate) SetUpdatedAt(v time.Time) *UserQuotaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserQuotaUpdate) SetUserID(v int) *UserQuotaUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableUserID(v *int) *UserQuotaUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserQuotaUpdate) AddUserID(v int) *UserQuotaUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetQuota sets the "quota" field.
func (_u *UserQuotaUpdate) SetQuota(v int64) *UserQuotaUpdate {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableQuota(v *int64) *UserQuotaUpdate {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *UserQuotaUpdate) AddQuota(v int64) *UserQuotaUpdate {
	_u.mutation.AddQuota(v)
	return _u
}

// SetUsedQuota sets the "used_quota" field.
func (_u *UserQuotaUpdate) SetUsedQuota(v int64) *UserQuotaUpdate {
	_u.mutation.ResetUsedQuota()
	_u.mutation.SetUsedQuota(v)
	return _u
}

// SetNillableUsedQuota sets the "used_quota" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableUsedQuota(v *int64) *UserQuotaUpdate {
	if v != nil {
		_u.SetUsedQuota(*v)
	}
	return _u
}

// AddUsedQuota adds value to the "used_quota" field.
func (_u *UserQuotaUpdate) AddUsedQuota(v int64) *UserQuotaUpdate {
	_u.mutation.AddUsedQuota(v)
	return _u
}

// SetGroup sets the "group" field.
func (_u *UserQuotaUpdate) SetGroup(v string) *UserQuotaUpdate {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableGroup(v *string) *UserQuotaUpdate {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetAffCode sets the "aff_code" field.
func (_u *UserQuotaUpdate) SetAffCode(v string) *UserQuotaUpdate {
	_u.mutation.SetAffCode(v)
	return _u
}

// SetNillableAffCode sets the "aff_code" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableAffCode(v *string) *UserQuotaUpdate {
	if v != nil {
		_u.SetAffCode(*v)
	}
	return _u
}

// ClearAffCode clears the value of the "aff_code" field.
func (_u *UserQuotaUpdate) ClearAffCode() *UserQuotaUpdate {
	_u.mutation.ClearAffCode()
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *UserQuotaUpdate) SetInviterID(v int) *UserQuotaUpdate {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableInviterID(v *int) *UserQuotaUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *UserQuotaUpdate) AddInviterID(v int) *UserQuotaUpdate {
	_u.mutation.AddInviterID(v)
	return _u
}

// ClearInviterID clears the value of the "inviter_id" field.
func (_u *UserQuotaUpdate) ClearInviterID() *UserQuotaUpdate {
	_u.mutation.ClearInviterID()
	return _u
}

// SetNotify sets the "notify" field.
func (_u *UserQuotaUpdate) SetNotify(v bool) *UserQuotaUpdate {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableNotify(v *bool) *UserQuotaUpdate {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// SetQuotaRemindThreshold sets the "quota_remind_threshold" field.
func (_u *UserQuotaUpdate) SetQuotaRemindThreshold(v int64) *UserQuotaUpdate {
	_u.mutation.ResetQuotaRemindThreshold()
	_u.mutation.SetQuotaRemindThreshold(v)
	return _u
}

// SetNillableQuotaRemindThreshold sets the "quota_remind_threshold" field if the given value is not nil.
func (_u *UserQuotaUpdate) SetNillableQuotaRemindThreshold(v *int64) *UserQuotaUpdate {
	if v != nil {
		_u.SetQuotaRemindThreshold(*v)
	}
	return _u
}

// AddQuotaRemindThreshold adds value to the "quota_remind_threshold" field.
func (_u *UserQuotaUpdate) AddQuotaRemindThreshold(v int64) *UserQuotaUpdate {
	_u.mutation.AddQuotaRemindThreshold(v)
	return _u
}

// Mutation returns the UserQuotaMutation object of the builder.
func (_u *UserQuotaUpdate) Mutation() *UserQuotaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserQuotaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserQuotaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserQuotaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserQuotaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserQuotaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userquota.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserQuotaUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserQuotaUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserQuotaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userquota.Table, userquota.Columns, sqlgraph.NewFieldSpec(userquota.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userquota.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userquota.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userquota.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(userquota.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(userquota.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsedQuota(); ok {
		_spec.SetField(userquota.FieldUsedQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsedQuota(); ok {
		_spec.AddField(userquota.FieldUsedQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(userquota.FieldGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.AffCode(); ok {
		_spec.SetField(userquota.FieldAffCode, field.TypeString, value)
	}
	if _u.mutation.AffCodeCleared() {
		_spec.ClearField(userquota.FieldAffCode, field.TypeString)
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(userquota.FieldInviterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(userquota.FieldInviterID, field.TypeInt, value)
	}
	if _u.mutation.InviterIDCleared() {
		_spec.ClearField(userquota.FieldInviterID, field.TypeInt)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(userquota.FieldNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuotaRemindThreshold(); ok {
		_spec.SetField(userquota.FieldQuotaRemindThreshold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRemindThreshold(); ok {
		_spec.AddField(userquota.FieldQuotaRemindThreshold, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userquota.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserQuotaUpdateOne is the builder for updating a single UserQuota entity.
type UserQuotaUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserQuotaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserQuotaUpdateOne) SetUpdatedAt(v time.Time) *UserQuotaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserQuotaUpdateOne) SetUserID(v int) *UserQuotaUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableUserID(v *int) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserQuotaUpdateOne) AddUserID(v int) *UserQuotaUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetQuota sets the "quota" field.
func (_u *UserQuotaUpdateOne) SetQuota(v int64) *UserQuotaUpdateOne {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableQuota(v *int64) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *UserQuotaUpdateOne) AddQuota(v int64) *UserQuotaUpdateOne {
	_u.mutation.AddQuota(v)
	return _u
}

// SetUsedQuota sets the "used_quota" field.
func (_u *UserQuotaUpdateOne) SetUsedQuota(v int64) *UserQuotaUpdateOne {
	_u.mutation.ResetUsedQuota()
	_u.mutation.SetUsedQuota(v)
	return _u
}

// SetNillableUsedQuota sets the "used_quota" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableUsedQuota(v *int64) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetUsedQuota(*v)
	}
	return _u
}

// AddUsedQuota adds value to the "used_quota" field.
func (_u *UserQuotaUpdateOne) AddUsedQuota(v int64) *UserQuotaUpdateOne {
	_u.mutation.AddUsedQuota(v)
	return _u
}

// SetGroup sets the "group" field.
func (_u *UserQuotaUpdateOne) SetGroup(v string) *UserQuotaUpdateOne {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableGroup(v *string) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetAffCode sets the "aff_code" field.
func (_u *UserQuotaUpdateOne) SetAffCode(v string) *UserQuotaUpdateOne {
	_u.mutation.SetAffCode(v)
	return _u
}

// SetNillableAffCode sets the "aff_code" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableAffCode(v *string) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetAffCode(*v)
	}
	return _u
}

// ClearAffCode clears the value of the "aff_code" field.
func (_u *UserQuotaUpdateOne) ClearAffCode() *UserQuotaUpdateOne {
	_u.mutation.ClearAffCode()
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *UserQuotaUpdateOne) SetInviterID(v int) *UserQuotaUpdateOne {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableInviterID(v *int) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *UserQuotaUpdateOne) AddInviterID(v int) *UserQuotaUpdateOne {
	_u.mutation.AddInviterID(v)
	return _u
}

// ClearInviterID clears the value of the "inviter_id" field.
func (_u *UserQuotaUpdateOne) ClearInviterID() *UserQuotaUpdateOne {
	_u.mutation.ClearInviterID()
	return _u
}

// SetNotify sets the "notify" field.
func (_u *UserQuotaUpdateOne) SetNotify(v bool) *UserQuotaUpdateOne {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableNotify(v *bool) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// SetQuotaRemindThreshold sets the "quota_remind_threshold" field.
func (_u *UserQuotaUpdateOne) SetQuotaRemindThreshold(v int64) *UserQuotaUpdateOne {
	_u.mutation.ResetQuotaRemindThreshold()
	_u.mutation.SetQuotaRemindThreshold(v)
	return _u
}

// SetNillableQuotaRemindThreshold sets the "quota_remind_threshold" field if the given value is not nil.
func (_u *UserQuotaUpdateOne) SetNillableQuotaRemindThreshold(v *int64) *UserQuotaUpdateOne {
	if v != nil {
		_u.SetQuotaRemindThreshold(*v)
	}
	return _u
}

// AddQuotaRemindThreshold adds value to the "quota_remind_threshold" field.
func (_u *UserQuotaUpdateOne) AddQuotaRemindThreshold(v int64) *UserQuotaUpdateOne {
	_u.mutation.AddQuotaRemindThreshold(v)
	return _u
}

// Mutation returns the UserQuotaMutation object of the builder.
func (_u *UserQuotaUpdateOne) Mutation() *UserQuotaMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserQuotaUpdate builder.
func (_u *UserQuotaUpdateOne) Where(ps ...predicate.UserQuota) *UserQuotaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserQuotaUpdateOne) Select(field string, fields ...string) *UserQuotaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserQuota entity.
func (_u *UserQuotaUpdateOne) Save(ctx context.Context) (*UserQuota, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserQuotaUpdateOne) SaveX(ctx context.Context) *UserQuota {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserQuotaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserQuotaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserQuotaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userquota.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserQuotaUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserQuotaUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserQuotaUpdateOne) sqlSave(ctx context.Context) (_node *UserQuota, err error) {
	_spec := sqlgraph.NewUpdateSpec(userquota.Table, userquota.Columns, sqlgraph.NewFieldSpec(userquota.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserQuota.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userquota.FieldID)
		for _, f := range fields {
			if !userquota.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userquota.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userquota.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userquota.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userquota.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(userquota.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(userquota.FieldQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsedQuota(); ok {
		_spec.SetField(userquota.FieldUsedQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsedQuota(); ok {
		_spec.AddField(userquota.FieldUsedQuota, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(userquota.FieldGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.AffCode(); ok {
		_spec.SetField(userquota.FieldAffCode, field.TypeString, value)
	}
	if _u.mutation.AffCodeCleared() {
		_spec.ClearField(userquota.FieldAffCode, field.TypeString)
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(userquota.FieldInviterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(userquota.FieldInviterID, field.TypeInt, value)
	}
	if _u.mutation.InviterIDCleared() {
		_spec.ClearField(userquota.FieldInviterID, field.TypeInt)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(userquota.FieldNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuotaRemindThreshold(); ok {
		_spec.SetField(userquota.FieldQuotaRemindThreshold, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaRemindThreshold(); ok {
		_spec.AddField(userquota.FieldQuotaRemindThreshold, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserQuota{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userquota.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
