// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/usersubscription"
)

// UserSubscriptionCreate is the builder for creating a UserSubscription entity.
type UserSubscriptionCreate struct {
	config
	mutation *UserSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSubscriptionCreate) SetCreatedAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSubscriptionCreate) SetUpdatedAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserSubscriptionCreate) SetUserID(v int) *UserSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *UserSubscriptionCreate) SetPlanID(v int) *UserSubscriptionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetQuotaRemaining sets the "quota_remaining" field.
func (_c *UserSubscriptionCreate) SetQuotaRemaining(v int64) *UserSubscriptionCreate {
	_c.mutation.SetQuotaRemaining(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserSubscriptionCreate) SetExpiresAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserSubscriptionCreate) SetStatus(v usersubscription.Status) *UserSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStatus(v *usersubscription.Status) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *UserSubscriptionCreate) SetOrderID(v string) *UserSubscriptionCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableOrderID(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (_c *UserSubscriptionCreate) Mutation() *UserSubscriptionMutation {
	return _c.mutation
}

// Save creates the UserSubscription in the database.
func (_c *UserSubscriptionCreate) Save(ctx context.Context) (*UserSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSubscriptionCreate) SaveX(ctx context.Context) *UserSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usersubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usersubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSubscription.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserSubscription.user_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "UserSubscription.plan_id"`)}
	}
	if _, ok := _c.mutation.QuotaRemaining(); !ok {
		return &ValidationError{Name: "quota_remaining", err: errors.New(`ent: missing required field "UserSubscription.quota_remaining"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserSubscription.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usersubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.status": %w`, err)}
		}
	}
	return nil
}

func (_c *UserSubscriptionCreate) sqlSave(ctx context.Context) (*UserSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSubscriptionCreate) createSpec() (*UserSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersubscription.Table, sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usersubscription.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(usersubscription.FieldPlanID, field.TypeInt, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.QuotaRemaining(); ok {
		_spec.SetField(usersubscription.FieldQuotaRemaining, field.TypeInt64, value)
		_node.QuotaRemaining = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usersubscription.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(usersubscription.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionUpsertOne {
	_c.conflict = opts
	return &UserSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionCreate) OnConflictColumns(columns ...string) *UserSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// UserSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one UserSubscription node.
	UserSubscriptionUpsertOne struct {
		create *UserSubscriptionCreate
	}

	// UserSubscriptionUpsert is the "OnConflict" setter.
	UserSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionUpsert) SetUpdatedAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateUpdatedAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserSubscriptionUpsert) SetUserID(v int) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateUserID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserSubscriptionUpsert) AddUserID(v int) *UserSubscriptionUpsert {
	u.Add(usersubscription.FieldUserID, v)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UserSubscriptionUpsert) SetPlanID(v int) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdatePlanID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserSubscriptionUpsert) AddPlanID(v int) *UserSubscriptionUpsert {
	u.Add(usersubscription.FieldPlanID, v)
	return u
}

// SetQuotaRemaining sets the "quota_remaining" field.
func (u *UserSubscriptionUpsert) SetQuotaRemaining(v int64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldQuotaRemaining, v)
	return u
}

// UpdateQuotaRemaining sets the "quota_remaining" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateQuotaRemaining() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldQuotaRemaining)
	return u
}

// AddQuotaRemaining adds v to the "quota_remaining" field.
func (u *UserSubscriptionUpsert) AddQuotaRemaining(v int64) *UserSubscriptionUpsert {
	u.Add(usersubscription.FieldQuotaRemaining, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionUpsert) SetExpiresAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateExpiresAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionUpsert) SetStatus(v usersubscription.Status) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStatus() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStatus)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *UserSubscriptionUpsert) SetOrderID(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateOrderID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldOrderID)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *UserSubscriptionUpsert) ClearOrderID() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldOrderID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionUpsertOne) UpdateNewValues() *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usersubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserSubscriptionUpsertOne) Ignore() *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionUpsertOne) DoNothing() *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionCreate.OnConflict
// documentation for more info.
func (u *UserSubscriptionUpsertOne) Update(set func(*UserSubscriptionUpsert)) *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateUpdatedAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserSubscriptionUpsertOne) SetUserID(v int) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserSubscriptionUpsertOne) AddUserID(v int) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateUserID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserSubscriptionUpsertOne) SetPlanID(v int) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserSubscriptionUpsertOne) AddPlanID(v int) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdatePlanID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetQuotaRemaining sets the "quota_remaining" field.
func (u *UserSubscriptionUpsertOne) SetQuotaRemaining(v int64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetQuotaRemaining(v)
	})
}

// AddQuotaRemaining adds v to the "quota_remaining" field.
func (u *UserSubscriptionUpsertOne) AddQuotaRemaining(v int64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddQuotaRemaining(v)
	})
}

// UpdateQuotaRemaining sets the "quota_remaining" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateQuotaRemaining() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateQuotaRemaining()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionUpsertOne) SetExpiresAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateExpiresAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionUpsertOne) SetStatus(v usersubscription.Status) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStatus() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetOrderID sets the "order_id" field.
func (u *UserSubscriptionUpsertOne) SetOrderID(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateOrderID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *UserSubscriptionUpsertOne) ClearOrderID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearOrderID()
	})
}

// Exec executes the query.
func (u *UserSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserSubscriptionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserSubscriptionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserSubscriptionCreateBulk is the builder for creating many UserSubscription entities in bulk.
type UserSubscriptionCreateBulk struct {
	config
	err      error
	builders []*UserSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserSubscription entities in the database.
func (_c *UserSubscriptionCreateBulk) Save(ctx context.Context) ([]*UserSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSubscriptionCreateBulk) SaveX(ctx context.Context) []*UserSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionUpsertBulk {
	_c.conflict = opts
	return &UserSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionCreateBulk) OnConflictColumns(columns ...string) *UserSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionUpsertBulk{
		create: _c,
	}
}

// UserSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserSubscription nodes.
type UserSubscriptionUpsertBulk struct {
	create *UserSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionUpsertBulk) UpdateNewValues() *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usersubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserSubscriptionUpsertBulk) Ignore() *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionUpsertBulk) DoNothing() *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *UserSubscriptionUpsertBulk) Update(set func(*UserSubscriptionUpsert)) *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateUpdatedAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserSubscriptionUpsertBulk) SetUserID(v int) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserSubscriptionUpsertBulk) AddUserID(v int) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateUserID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserSubscriptionUpsertBulk) SetPlanID(v int) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserSubscriptionUpsertBulk) AddPlanID(v int) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdatePlanID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetQuotaRemaining sets the "quota_remaining" field.
func (u *UserSubscriptionUpsertBulk) SetQuotaRemaining(v int64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetQuotaRemaining(v)
	})
}

// AddQuotaRemaining adds v to the "quota_remaining" field.
func (u *UserSubscriptionUpsertBulk) AddQuotaRemaining(v int64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddQuotaRemaining(v)
	})
}

// UpdateQuotaRemaining sets the "quota_remaining" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateQuotaRemaining() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateQuotaRemaining()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateExpiresAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionUpsertBulk) SetStatus(v usersubscription.Status) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStatus() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetOrderID sets the "order_id" field.
func (u *UserSubscriptionUpsertBulk) SetOrderID(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateOrderID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *UserSubscriptionUpsertBulk) ClearOrderID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearOrderID()
	})
}

// Exec executes the query.
func (u *UserSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
