// Code generated by ent, DO NOT EDIT.

package rechargeorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldOrderID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldAmount, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// TradeID applies equality check predicate on the "trade_id" field. It's identical to TradeIDEQ.
func TradeID(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldTradeID, v))
}

// PaidAmount applies equality check predicate on the "paid_amount" field. It's identical to PaidAmountEQ.
func PaidAmount(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAmount, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldDescription, v))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPackageID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldOrderID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldType, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodIsNil applies the IsNil predicate on the "payment_method" field.
func PaymentMethodIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPaymentMethod))
}

// PaymentMethodNotNil applies the NotNil predicate on the "payment_method" field.
func PaymentMethodNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPaymentMethod))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// TradeIDEQ applies the EQ predicate on the "trade_id" field.
func TradeIDEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldTradeID, v))
}

// TradeIDNEQ applies the NEQ predicate on the "trade_id" field.
func TradeIDNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldTradeID, v))
}

// TradeIDIn applies the In predicate on the "trade_id" field.
func TradeIDIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldTradeID, vs...))
}

// TradeIDNotIn applies the NotIn predicate on the "trade_id" field.
func TradeIDNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldTradeID, vs...))
}

// TradeIDGT applies the GT predicate on the "trade_id" field.
func TradeIDGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldTradeID, v))
}

// TradeIDGTE applies the GTE predicate on the "trade_id" field.
func TradeIDGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldTradeID, v))
}

// TradeIDLT applies the LT predicate on the "trade_id" field.
func TradeIDLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldTradeID, v))
}

// TradeIDLTE applies the LTE predicate on the "trade_id" field.
func TradeIDLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldTradeID, v))
}

// TradeIDContains applies the Contains predicate on the "trade_id" field.
func TradeIDContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldTradeID, v))
}

// TradeIDHasPrefix applies the HasPrefix predicate on the "trade_id" field.
func TradeIDHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldTradeID, v))
}

// TradeIDHasSuffix applies the HasSuffix predicate on the "trade_id" field.
func TradeIDHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldTradeID, v))
}

// TradeIDIsNil applies the IsNil predicate on the "trade_id" field.
func TradeIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldTradeID))
}

// TradeIDNotNil applies the NotNil predicate on the "trade_id" field.
func TradeIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldTradeID))
}

// TradeIDEqualFold applies the EqualFold predicate on the "trade_id" field.
func TradeIDEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldTradeID, v))
}

// TradeIDContainsFold applies the ContainsFold predicate on the "trade_id" field.
func TradeIDContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldTradeID, v))
}

// PaidAmountEQ applies the EQ predicate on the "paid_amount" field.
func PaidAmountEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAmount, v))
}

// PaidAmountNEQ applies the NEQ predicate on the "paid_amount" field.
func PaidAmountNEQ(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaidAmount, v))
}

// PaidAmountIn applies the In predicate on the "paid_amount" field.
func PaidAmountIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaidAmount, vs...))
}

// PaidAmountNotIn applies the NotIn predicate on the "paid_amount" field.
func PaidAmountNotIn(vs ...int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaidAmount, vs...))
}

// PaidAmountGT applies the GT predicate on the "paid_amount" field.
func PaidAmountGT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaidAmount, v))
}

// PaidAmountGTE applies the GTE predicate on the "paid_amount" field.
func PaidAmountGTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaidAmount, v))
}

// PaidAmountLT applies the LT predicate on the "paid_amount" field.
func PaidAmountLT(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaidAmount, v))
}

// PaidAmountLTE applies the LTE predicate on the "paid_amount" field.
func PaidAmountLTE(v int64) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaidAmount, v))
}

// PaidAmountIsNil applies the IsNil predicate on the "paid_amount" field.
func PaidAmountIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPaidAmount))
}

// PaidAmountNotNil applies the NotNil predicate on the "paid_amount" field.
func PaidAmountNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPaidAmount))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPaidAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldExpiresAt))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldContainsFold(FieldDescription, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v int) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldLTE(FieldPackageID, v))
}

// PackageIDIsNil applies the IsNil predicate on the "package_id" field.
func PackageIDIsNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldIsNull(FieldPackageID))
}

// PackageIDNotNil applies the NotNil predicate on the "package_id" field.
func PackageIDNotNil() predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.FieldNotNull(FieldPackageID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RechargeOrder) predicate.RechargeOrder {
	return predicate.RechargeOrder(sql.NotPredicates(p))
}
