// Code generated by ent, DO NOT EDIT.

package userquota

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userquota type in the database.
	Label = "user_quota"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldQuota holds the string denoting the quota field in the database.
	FieldQuota = "quota"
	// FieldUsedQuota holds the string denoting the used_quota field in the database.
	FieldUsedQuota = "used_quota"
	// FieldGroup holds the string denoting the group field in the database.
	FieldGroup = "group"
	// FieldAffCode holds the string denoting the aff_code field in the database.
	FieldAffCode = "aff_code"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldNotify holds the string denoting the notify field in the database.
	FieldNotify = "notify"
	// FieldQuotaRemindThreshold holds the string denoting the quota_remind_threshold field in the database.
	FieldQuotaRemindThreshold = "quota_remind_threshold"
	// Table holds the table name of the userquota in the database.
	Table = "user_quota"
)

// Columns holds all SQL columns for userquota fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldQuota,
	FieldUsedQuota,
	FieldGroup,
	FieldAffCode,
	FieldInviterID,
	FieldNotify,
	FieldQuotaRemindThreshold,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultQuota holds the default value on creation for the "quota" field.
	DefaultQuota int64
	// DefaultUsedQuota holds the default value on creation for the "used_quota" field.
	DefaultUsedQuota int64
	// DefaultGroup holds the default value on creation for the "group" field.
	DefaultGroup string
	// DefaultNotify holds the default value on creation for the "notify" field.
	DefaultNotify bool
	// DefaultQuotaRemindThreshold holds the default value on creation for the "quota_remind_threshold" field.
	DefaultQuotaRemindThreshold int64
)

// OrderOption defines the ordering options for the UserQuota queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByQuota orders the results by the quota field.
func ByQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuota, opts...).ToFunc()
}

// ByUsedQuota orders the results by the used_quota field.
func ByUsedQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedQuota, opts...).ToFunc()
}

// ByGroup orders the results by the group field.
func ByGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroup, opts...).ToFunc()
}

// ByAffCode orders the results by the aff_code field.
func ByAffCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffCode, opts...).ToFunc()
}

// ByInviterID orders the results by the inviter_id field.
func ByInviterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterID, opts...).ToFunc()
}

// ByNotify orders the results by the notify field.
func ByNotify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotify, opts...).ToFunc()
}

// ByQuotaRemindThreshold orders the results by the quota_remind_threshold field.
func ByQuotaRemindThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaRemindThreshold, opts...).ToFunc()
}
